name: Build GKI Kernel - Android 13 5.15

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Do you want to create a release?'
        required: true
        type: boolean
        default: true
      kernelsu_branch:
        description: "Choose ksu branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Dev
      kernelsu_branch_other:
        description: "If 'Other' is selected, specify your custom branch"
        required: false
        type: string
        default: ""

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:

      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F message_thread_id="${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}" \
            -F text="
            🚀 Build started for Vermeer GKI Kernel! 
            📦 *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})
            🗂️ *Branch:* ${{ github.ref_name }}
            ✏️ *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            [🔗 View GitHub Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
            -F parse_mode="Markdown"
            
      - name: Get commit hash or tag and generate URL for KernelSU-Next
        run: |
          REPO_URL="https://github.com/KernelSU-Next/KernelSU-Next.git"
          REPO_URL2="KernelSU-Next/KernelSU-Next"
          if [ "${{ inputs.kernelsu_branch }}" == "Stable" ]; then
            TAG=$(git ls-remote --tags --sort=-v:refname $REPO_URL | grep -o 'refs/tags/.*' | cut -d'/' -f3 | head -n1)
            KSU_REF=$TAG
            KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
          elif [ "${{ inputs.kernelsu_branch }}" == "Dev" ]; then
            COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/next | awk '{ print $1 }')
            KSU_REF=$COMMIT_HASH
            KSU_URL="https://github.com/$REPO_URL2/commit/$COMMIT_HASH"
          elif [ "${{ inputs.kernelsu_branch }}" == "Other" ] && [ -n "${{ inputs.kernelsu_branch_other }}" ]; then
            TAG=${{ inputs.kernelsu_branch_other }}
            if git ls-remote --tags $REPO_URL | grep -q "refs/tags/$TAG"; then
              KSU_REF=$TAG
              KSU_URL="https://github.com/$REPO_URL2/releases/tag/$TAG"
            else
              COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$TAG | awk '{ print $1 }')
              KSU_REF=$COMMIT_HASH
              KSU_URL="https://github.com/$REPO_URL2/commit/$COMMIT_HASH"
            fi
          else
            echo "Error: Invalid branch configuration" >&2
            exit 1
          fi
          echo "KSU_REF=$KSU_REF" >> $GITHUB_ENV
          echo "KSU_URL=$KSU_URL" >> $GITHUB_ENV

      - name: Get SUSFS commit hashes and generate commit URLs
        run: |
          GITLAB_OWNER="simonpunk"
          GITLAB_REPO="susfs4ksu"
          BRANCH_NAME="gki-android13-5.15"
          COMMIT_HASH=$(git ls-remote https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO.git refs/heads/$BRANCH_NAME | awk '{ print $1 }')
          if [[ -n "$COMMIT_HASH" ]]; then
            COMMIT_URL="https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO/-/commit/$COMMIT_HASH"
            echo "gki_android13_5_15 Commit: $COMMIT_HASH"
            echo "gki_android13_5_15 Commit URL: $COMMIT_URL"
            echo "COMMIT_HASH_gki_android13_5_15=$COMMIT_HASH" >> "$GITHUB_ENV"
            echo "COMMIT_URL_gki_android13_5_15=$COMMIT_URL" >> "$GITHUB_ENV"
          fi

      - name: Generate and Create New Tag
        run: |
          LATEST_TAG=$(gh api repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/tags --jq '.[0].name')
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v1.5.9-r0"
          fi
          NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Set release body
        run: |
          cat << 'EOF' > release_body.md
          This release contains KernelSU-Next ${{ inputs.kernelsu_branch }} and SUSFS v1.5.9

          Features:
          -> KernelSU-Next-${{ inputs.kernelsu_branch }}
          -> SUSFS v1.5.9
          -> Manual Hooks
          -> Wireguard Support
          -> BBR Support

          Notes:
          This is a MODIFIED kernel only meant for VERMEER devices a.k.a Redmi K70 / Poco F6 Pro, running on HyperOS 1.0.6. If you do not have this device, please do not flash this.

          Module:
          -> https://github.com/sidex15/ksu_module_susfs

          Managers:
          -> https://github.com/KernelSU-Next/KernelSU-Next

          Commit Hashes (at the time of release):
          -> KernelSU-Next: [${{ env.KSU_REF }}](${{ env.KSU_URL }})
          -> SUSFS4KSU:
            -> gki-android13-5.15: [${{ env.COMMIT_HASH_gki_android13_5_15 }}](${{ env.COMMIT_URL_gki_android13_5_15 }})
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          prerelease: true
          files: ""
          name: ${{ env.RELEASE_NAME }}
          body_path: release_body.md
